### PR TITLE
Failing linter job on Windows

### LINKED ISSUE #39: New features to get to a 1.0.0 release
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/sflags/releases).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Following features would be useful to get a full featured release

- [x] Add Required Flag tag #40 
- [ ] ~~Add support for Viper #6  #~~
- [ ] Add support for map values #7 
- [ ] Add support for multiple env vars #41 
- [ ] Flag Type for setting date using natural language #8 (https://github.com/olebedev/when)

### PR DESCRIPTION
**Pull request by abitrolly**
Reverting https://github.com/urfave/sflags/commit/76f9d1865fb3b667bbefa8b90f272c6bfdcc3836#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2L19 and fixing linter test on Windows.

It needed proper LF line endings.

## What type of PR is this?

_(REQUIRED)_

- bug
- cleanup
- documentation
- feature

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

**Review by dearchap — APPROVED** [review]

**Comment by abitrolly** [comment]
Log is not very informative. 1888 lines. 
```
\033[32;01mRun vet\033[0m
\033[32;01mRun golangci-lint\033[0m
cmd\genvalues\main.go:1: File is not `goimports`-ed (goimports)
// This generator is for internal usage only.
//
// It generates values described in values.json.
package main
...
// Parse parses cfg, that is a pointer to some structure,
// puts it to the new flag.FlagSet and returns it.
func Parse(cfg interface{}, optFuncs ...sflags.OptFunc) ([]cli.Flag, error) {
	flags := make([]cli.Flag, 0)
	err := ParseTo(cfg, &flags, optFuncs...)
	if err != nil {
		return nil, err
	}
	return flags, nil
}
make: *** [Makefile:33: check] Error 1
Error: Process completed with exit code 1.
```
But on Mac there is no `cmd\genvalues\main.go:1: File is not `goimports`-ed (goimports)` message.

**Comment by abitrolly** [comment]
@dearchap fixed.

**Review by Juneezee — APPROVED** [review]
This issue was also discussed in https://github.com/golangci/golangci-lint/issues/580#issuecomment-704913317

**Comment by abitrolly** [comment]
Opened https://github.com/golang/go/issues/70297 to improve `goimports` error message.

**Pull request merged**
